/* Create new database */
CREATE DATABASE BOOKINGDB;
/* Use this database */
USE BOOKINGDB;

/* Create new table */
CREATE TABLE USER (
ID INT NOT NULL AUTO_INCREMENT,
NAME VARCHAR(30) NOT NULL,
ADDRESS VARCHAR(50) NOT NULL,
MOBILE VARCHAR(10) NOT NULL,
PRIMARY KEY(ID));
/* Insert data to this table */
INSERT INTO USER (NAME, ADDRESS, MOBILE) VALUE ("Hoang", "Ha Noi", "0912345678"), ("Minh", "Da Nang", "0988888888"), ("Phuong", "HCM", "0986868686");

/* Create new table */
CREATE TABLE BOOKING(
ID INT NOT NULL AUTO_INCREMENT,
START_DATE_TIME DATE,
STOP_DATE_TIME DATE,
PAYED BOOLEAN,
PRIMARY KEY(ID));
/* Insert data to this table */
INSERT INTO BOOKING (START_DATE_TIME, STOP_DATE_TIME, PAYED) 
VALUE ("2021-02-26", "2021-02-28", TRUE), ("2021-03-01", "2021-03-08", TRUE), ("2021-03-09", "2021-03-11", FALSE);

/* Create new table */
CREATE TABLE ROOM (
ID_NUMBER INT NOT NULL AUTO_INCREMENT,
GRACE_PERIOD_HOURS INT NOT NULL,
FIXED_BOOKING_CHARGE INT NOT NULL,
PRIMARY KEY(ID_Number));
/* Insert data to this table */
INSERT INTO ROOM (GRACE_PERIOD_HOURS, FIXED_BOOKING_CHARGE) 
VALUE ("1", "60000"), ("12", "130000"), ("24", "270000");